### ISSUE TITLE
Confluence example appears to be missing the trailing "</script>" tag

### ISSUE THREAD

**Issue by speedyleion** [mscgenjs/mscgenjs-inpage#4]
### steps taken

Copy the example verbatim into a confluence html macro, from https://mscgen.js.org/embed.html#embedding-in-atlassian-confluence
Save, confluence displays nothing.
[Sorry not at work so don't recall the version :( ]

### expected
MSC image should be shown

### found
If  I added an ending script tag to the provided example it worked.

```
<script src="https://mscgen.js.org/mscgen-inpage.js" defer></script>

<code class="mscgen_js">
msc {
    a [label="Entity A"], b [label="Entity B"];

    a <<=>> b [label="testing (confluence)"];
    b note b [label="MscGen embedded in a confluence page!"];
}
</code>
```

### notes
I did a quick dig to try and find the source for https://mscgen.js.org/embed.html#embedding-in-atlassian-confluence to create a pull request but i failed.

**Comment by sverweij** [comment]
Thanks for spotting that (and for your excellent bug report)!

I forgot to replace the < with an &lt; in </script> 😊  I've fixed & published it.

The sources for the mscgen.js online documentation are still in sverweij/mscgen_js - I should probably change that some time :-)
